version: "3"
services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "5000:80/tcp"
    environment:
      TZ: "America/Argentina/Buenos_Aires"
      WEBPASSWORD: "openmediavault"
    # Volumes store your data between container upgrades
    volumes:
      - /srv/dev-disk-by-uuid-11d78789-30d2-4e14-bf2a-e97699978c67/pihole/pihole:/etc/pihole
      - /srv/dev-disk-by-uuid-11d78789-30d2-4e14-bf2a-e97699978c67/pihole/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped

volumes:
  etc-pihole:
  etc-dnsmasq:
