version: "3"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001 # srv-plex user
      - PGID=1001 # srv-plex group
      - TZ=America/Argentina/Buenos_Aires
      - VERSION=docker
    volumes:
      - /srv/dev-disk-by-uuid-11d78789-30d2-4e14-bf2a-e97699978c67/plex/config:/config
      - /srv/dev-disk-by-uuid-11d78789-30d2-4e14-bf2a-e97699978c67/plex/tv:/tv
      - /srv/dev-disk-by-uuid-11d78789-30d2-4e14-bf2a-e97699978c67/plex/movies:/movies
    restart: unless-stopped
  torrent:
    image: linuxserver/transmission
    container_name: torrent
    environment:
      - PUID=1001 # srv-plex user
      - PGID=1001 # srv-plex group
      - TZ=${CONTAINERS_TZ-America/Argentina/Buenos_Aires}
      - USER=${PLEX_USER:?Missing plex username (PLEX_USER)}
      - PASS=${PLEX_PASSWORD:?Missing plex password (PLEX_PASSWORD)}
    volumes:
      - /srv/dev-disk-by-uuid-11d78789-30d2-4e14-bf2a-e97699978c67/plex/tconfig:/config
      - /srv/dev-disk-by-uuid-11d78789-30d2-4e14-bf2a-e97699978c67/plex:/downloads
    ports:
      - 8080:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
