version: "3"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=${CONTAINERS_UID:?}
      - PGID=${CONTAINERS_GID:?}
      - TZ=${CONTAINERS_TZ:?}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - ${PLEX_PORT-32400}:32400
    volumes:
      - ${CONTAINERS_PATH:?}/${BASE_PATH:?}/plex/config:/config
      - ${CONTAINERS_PATH:?}/${BASE_PATH:?}/plex/tv:/tv
      - ${CONTAINERS_PATH:?}/${BASE_PATH:?}/plex/movies:/movies
    restart: unless-stopped
    networks:
      - services-network
  torrent:
    image: linuxserver/qbittorrent
    container_name: torrent
    environment:
      - PUID=${CONTAINERS_UID:?}
      - PGID=${CONTAINERS_GID:?}
      - TZ=${CONTAINERS_TZ:?}
      - WEBUI_PORT=${TORRENT_WEB_PORT-9091}
    volumes:
      - ${CONTAINERS_PATH:?}/${BASE_PATH:?}/torrent/config:/config
      - ${CONTAINERS_PATH:?}/${BASE_PATH:?}/torrent/downloads:/downloads
    ports:
      - ${TORRENT_WEB_PORT-9091}:9091
      - ${TORRENT_PORT-6881}:6881
      - ${TORRENT_PORT-6881}:6881/udp
    restart: unless-stopped
    networks:
      - services-network

networks:
  services-network:
    external: true
    name: ${SERVICES_NETWORK_NAME:?}
